name: Lambda Boilerplate

on: [push]
jobs:
  terraform-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up dependencies
      run: |
        . script/bootstrap
    - name: Lint
      run: |
        PROJECT=app make terraform-lint
        PROJECT=bootstrap make terraform-lint
