# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Lambda Boilerplate

on: [push, pull_request]
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: gabrielfalcao/pyenv-action@v5
      with:
        default: "3.8"
        command: pip install -U pip
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: . script/bootstrap
    - name: Validate templates
      run: (cd infrastructure && sceptre validate app/app.yaml && sceptre validate bootstrap/bootstrap.yaml)
